build:
 version: 1.0
 #SPRING_DATASOURCE_PASSWORD: "root1"

spring:
 datasource:
  password: "root1"

 
loans:
 message: "Welcome to EazyBank loans services development APIs"
 contactDetails:
  name: "John doe - Developer -  Loans Development Lead"
  email: "john@eazybank.com"
 onCallSupport:
  - (333) 555-1234
  - (333) 523-1345      
